import {
  FaReact,
  FaSass,
  FaNodeJs,
  FaHtml5,
  FaGitAlt,
  FaGithub,
  FaBootstrap,
  FaCss3Alt,
} from "react-icons/fa"
import {
  SiMicrosoftaccess,
  SiMicrosoftpowerpoint,
  SiMicrosoftexcel,
  SiMicrosoftword,
  SiThreedotjs,
  SiBlender,
  SiSketchup,
  SiJavascript,
  SiAdobephotoshop,
  SiFirebase,
  SiMysql,
  SiSupabase,
} from "react-icons/si"
const iconData = [
  { name: "React", icon: FaReact },
  { name: "Sass", icon: FaSass },
  { name: "Node.js", icon: FaNodeJs },
  { name: "HTML5", icon: FaHtml5 },
  { name: "Access", icon: SiMicrosoftaccess },
  { name: "PowerPoint", icon: SiMicrosoftpowerpoint },
  { name: "Excel", icon: SiMicrosoftexcel },
  { name: "Word", icon: SiMicrosoftword },
  { name: "Three.js", icon: SiThreedotjs },
  { name: "Blender", icon: SiBlender },
  { name: "Git", icon: FaGitAlt },
  { name: "GitHub", icon: FaGithub },
  { name: "Sketchup", icon: SiSketchup },
  { name: "Bootstrap", icon: FaBootstrap },
  { name: "Css3", icon: FaCss3Alt },
  { name: "Javascript", icon: SiJavascript },
  { name: "Photoshop", icon: SiAdobephotoshop },
  { name: "Firebase", icon: SiFirebase },
  { name: "MySql", icon: SiMysql },
  { name: "Supabase", icon: SiSupabase },
]
export default iconData
